name: Lint PHP

on:
  push:
    branches:
      - dev
      - main
    paths:
      - '**/*.php'
      - 'composer.json'
      - 'composer.lock'
      - 'phpstan.neon'
      - 'phpstan.neon.dist'
      - 'psalm.xml'
      - '.github/workflows/lint-php.yml'

  pull_request:
    branches:
      - dev
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  php:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - uses: ./.github/actions/setup-bun-deps

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'

      - name: Install Composer dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Lint PHP
        run: bun run lint-php
